menu:
    博客: /
    歸檔: /archives/
    GitHub: https://github.com/Yumiko-Liu

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2017